const SETTING_QUEEN_BEE_LIFESPAN = 100;
const SETTING_QUEEN_BEE_HITPOINT = 8;

const SETTING_WORKER_BEE_LIFESPAN = 75;
const SETTING_WORKER_BEE_HITPOINT = 10;

const SETTING_DRONE_BEE_LIFESPAN = 50;
const SETTING_DRONE_BEE_HITPOINT = 12;

const SETTING_NUM_OF_WORKER_BEES = 5;
const SETTING_NUM_OF_DRONE_BEES = 8;

const SETTING_QUEEN_BEE_IMAGE_URL = "img/Bee/QueenBee.png";
const SETTING_WORKER_BEE_IMAGE_URL = "img/Bee/WorkerBee.png";
const SETTING_DRONE_BEE_IMAGE_URL = "img/Bee/DroneBee.png";
const SETTING_DEAD_BEE_URL = "img/Bee/DeadBee.png";

const STATE_PLAYING = 0;
const STATE_WON = 1;